ALTER TABLE SLIDE DROP CONSTRAINT FK_SLIDE_CONFIGURACAO_ID;
DROP TABLE USUARIO CASCADE;
DROP TABLE CONFIGURACAO CASCADE;
DROP TABLE SLIDE CASCADE;
DROP TABLE ACESSO CASCADE;
DROP SEQUENCE ACESSO_SEQ;
DROP SEQUENCE SLIDE_SEQ;
DROP SEQUENCE USUARIO_SEQ;